<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix</title>

    <script src="https://kit.fontawesome.com/ba6e00a3e9.js" crossorigin="anonymous"></script>
    
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">



    

    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>


    <link rel="stylesheet" href="/css/style.css">
    
</head>

<body>
    <div class="cont-global">
        <div class="overlay"></div>

        <nav>
            <ul class="opcoes-usuario">
    
                <li>
                    <img src="./img/avatar.png">
    
                    <div>
                        <label for="trocarPerfil">Will</label>
                        <a id="trocarPerfil" href="#">Trocar de perfil</a>
                    </div>
    
                </li>
    
                <li><a href="#">Conta</a></li>
                <li><a href="#">Centro de ajuda</a></li>
                <li><a href="#">Sair da Netflix</a></li>
            </ul>
    
            <ul class="tipos-de-filmes">
    
                <li class="tipos-defilmes-item ativado">
                    <div class="sinal"></div>
                    <a href="#">Início</a>
                </li>
    
                <li class="tipos-defilmes-item"><a href="#">Minha Lista</a></li>
                <li class="tipos-defilmes-item"><a href="#">Programas de TV Japoneses</a></li>
                <li class="tipos-defilmes-item"><a href="#">Séries escandinavas</a></li>
                <li class="tipos-defilmes-item"><a href="#">Filmes colombianos</a></li>
                <li class="tipos-defilmes-item"><a href="#">Séries dramaáticas</a></li>
                <li class="tipos-defilmes-item"><a href="#">Filmes de Terror</a></li>
                <li class="tipos-defilmes-item"><a href="#">Faroestes</a></li>
            </ul>
        </nav>

        <header>
            <div class="container-header">

                <div class="container-hamburguer-logo">
                    <div class="hamburguer">
                        <span class="linha-hamburguer">
                        </span>
                    </div>

                    <img width="85px" src="./img/logo.png" alt="Netflix">

                    <div class="dispositivos-grandes">
                        <ul>
                            <li><a href="#">Navegar</a></li>
                            <li><a href="#">Infantil</a></li>
                        </ul>
                    </div>
                </div>


                <div class="container-buscar">
                    <input type="text" placeholder="Buscar">
                </div>
    
            </div>
        </header>
    
        <?= $this->content(); ?> 
    
    </div>
    
    


   
    <script
    src="https://code.jquery.com/jquery-3.6.0.slim.js"
    integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
    crossorigin="anonymous"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.27/ua-parser.min.js" integrity="sha512-/s1CZN4F+eS07hx0I8c9dzKS0/geGuZS3wRJDekq0NRy3lqLkiIm3dZ8kY+6123E7BY3j/d9VYCUTPOYQ/Obtw==" crossorigin="anonymous"></script>
    
    

    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    
    <script src="/js/script.js" type="module"></script>
</body>

</html>